export const envContent = `
COMPANY_NAME = ''
CORS_ALLOWED_WEB = ["http://localhost:4001"]
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PASSWORD = ''
EMAIL_USER = ''
JWT_ENCRYPTION =
LOGO = logo.png
PORT = 7000
TYPEORM_CONNECTION = mysql
TYPEORM_DATABASE = 
TYPEORM_ENTITIES = staging/entities/*.js
TYPEORM_HOST = host.docker.internal
TYPEORM_PASSWORD = root
TYPEORM_PORT = 3306
TYPEORM_USERNAME = root
VERIFICATION_LINK = 

INTERNAL_API_KEY = ''
ATTACHMENT_TOKEN_KEY = ''
ATTACHMENT_EXPIRY_MINUTES = 10
RESPONSE_WAIT_TIME = 2

LOGIN_ATTEMPTS = 
USE_2FA = 'false'
INITIAL_ADMIN_PASSWORD =
`;
